### ISSUE TITLE
Latest ReleaseFast AND ReleaseSafe Windows X86_64 insta-crashes with mystery unhandled error

### ISSUE THREAD

**Issue by Vintagemotors** [Beyley/ztyping#6]
Popup says to report so here it is :) 

Edit: 
For anyone in the future who has this issue - go to the Actions tab click summary, scroll down, choose the fragment appropriate for your platform, download it, extract it, download UTyping [https://tosk.jp/utyping/](url), extract it, take all of the contents of the fragment folder and drag them into the UTYping folder, after that run ztyping."yourplatformsbinaryextension" and it should work.

**Comment by Beyley** [comment]
you likely are missing required files, you should place the executables into a downloaded [UTyping](https://tosk.jp/utyping/) folder, so it can use the songs, config, and convert file

**Comment by Vintagemotors** [comment]
Yep, that did the trick - Thanks!
